### ISSUE TITLE
Question: Can I use this library to test Angular2?

### ISSUE THREAD

**Issue by sisillV** [bbaia/protractor-net#65] opened 2017-04-27 08:56 UTC
Hi Protractor-net Team,
I try to use your library to test Angular2 cli application but I have error every time.
Can I use this library to test Angular2?

Best Regards,
Stanislava

**Comment by jjldickinson** [comment] 2017-12-12 20:07
See issue 39 (closed; [https://github.com/bbaia/protractor-net/issues/39](url)), which suggests that you can.
Duplicate of #39 .

**Comment by bbaia** [comment] 2018-01-14 10:56
Thanks @jjldickinson

**Closed by bbaia** 2018-01-14 10:56 UTC
